name: Docker Build

on:
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Target ARC name used for `run-on` in job'
        default: ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.arc_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-repo:latest
